apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-common
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/openstack-common
    repoURL: https://github.com/leifmadsen/rhoso-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
