apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: repo-gitlab-cee
    namespace: openshift-gitops
    literals:
      - insecure=true
      - project=default
      - type=git
      - url=https://gitlab.cee.redhat.com/lmadsen/rhoso-gitops.git

patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: repo-gitlab-cee
        namespace: openshift-gitops
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repository

resources:
  - gitops-subscribe.yaml
  - openstack-clusterrole.yaml
  - argocd-openshift-gitops.yaml
