apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  name: baremetal-operator-config
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base/baremetal-operator/config
    repoURL: https://gitlab.cee.redhat.com/lmadsen/rhoso-gitops.git
    targetRevision: main
    kustomize:
      patches:
        - target:
            kind: Namespace
          patch: |-
            - op: add
              path: /metadata/labels
              value:
                argocd.argoproj.io/managed-by: openshift-gitops
  syncPolicy:
    automated: {}

